=== fazyloff/XSD/SD/sdTaskRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="TaskRequest">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Author"/>
        <xs:element ref="Analitic"/>
        <xs:element ref="TaskDate"/>
        <xs:element ref="BUId"/>
        <xs:element ref="CategoryId"/>
        <xs:element ref="Subject"/>
        <xs:element ref="Body"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Author" type="email"/>
  <xs:element name="Analitic" type="email"/>
  <xs:element name="TaskDate" type="xs:dateTime"/>
  <xs:element name="BUId" type="xs:integer"/>
  <xs:element name="CategoryId" type="xs:integer"/>
  <xs:element name="Subject" type="xs:string"/>
  <xs:element name="Body" type="xs:string"/>
   <xs:simpleType name="email"> 
    <xs:restriction base="xs:string"> 
      <xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
    </xs:restriction> 
  </xs:simpleType> 
</xs:schema>

=== fazyloff/XSD/SD/sdSample.xml
<?xml version="1.0"?>
<TaskRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sdTaskRequest.xsd">
<Author>user@gradient.ru</Author>
<Analitic>ubaAnalitic@gradient.ru</Analitic>
<TaskDate>2018-08-09T14:15:16</TaskDate>
<BUId>1</BUId>
<CategoryId>3</CategoryId>
<Subject>Ошибка! Помогите!</Subject>
<Body>Я не знаю, что делать! Все сломалось,
hdkdgh"
 "аиавивэптпаэпат"</Body>
</TaskRequest>
<!--
заявитель - будет в типа пересылаемом письме после "FROM:" - будет и в SD как заявитель
аналитик УБА - от кого письмо на сервис SD - будем в SD как исполнители
Дата  - Дата письма, если будет надо потом поменяем в SD
БЕ заявителя - будем брать из AD или ещё откуда-то 
БЕ исходная - она будет фиксироваться в письме, если мы её знаем  (вот её куда-то засунуть)
Категория - вот её куда-то засунуть
Тема - тема письма
-->
